### PR TITLE
build: adding SLSA provenance generation for build artifacts and containers

### PR DESCRIPTION
**Pull request by rsoberano-ld**
**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

https://launchdarkly.atlassian.net/browse/SEC-5331

**Describe the solution you've provided**

Adding SLSA provenance generation for artifacts and containers built for ld-relay. Based off goreleaser's guidance for SLSA provenance generation with goreleaser: https://goreleaser.com/blog/slsa-generation-for-your-artifacts/#slsa-github-generator

### CODE REVIEW

**Comment by rsoberano-ld** [comment]
Could use some help testing the Docker pieces next week. I'm not sure if the container provenance generator handles generating provenance for multiple images or if we need to pass in one image at a time; this would be sorted out in testing though.

**Comment by cwaldren-ld** [comment]
https://github.com/launchdarkly/ld-relay/actions/runs/9355788264

**Comment by cwaldren-ld** [comment]
https://github.com/launchdarkly/ld-relay/actions/runs/9358313251

**Comment by rsoberano-ld** [comment]
> https://github.com/launchdarkly/ld-relay/actions/runs/9358313251

I think this might have to do with the fact that the 8.5.1 tag already exists from a previous commit, but my branch thinks 8.5.1 is the next release because it only knows of 8.5.0? Not sure how/why though, not completely familiar with how goreleaser comes up with these tags

**Comment by cwaldren-ld** [comment]
Attempting again: https://github.com/launchdarkly/ld-relay/actions/runs/9371869337

**Comment by rsoberano-ld** [comment]
Thanks for rerunning! That's fixed the `goreleaser` error and gotten us to the provenance generation steps - need to debug a few things with those workflows this afternoon and will ping you when we're ready to retest.

**Comment by rsoberano-ld** [comment]
Sorted out the issue with generating provenance for binaries/zip files, just had an incorrect variable.

For docker images though, we need to pass in the manifest name from the `Docker Manifests` artifact that goreleaser creates after publishing. It looks like [manual builds don't create this artifact though](https://github.com/launchdarkly/ld-relay/actions/runs/9371869337/job/25802110736), whereas [builds triggered by release-please do](https://github.com/launchdarkly/ld-relay/actions/runs/9392710779/job/25867426137) - @cwaldren-ld would you happen to know why this happens?

**Comment by rsoberano-ld** [comment]
Oh wait I might know why, the docker manifest only gets created by goreleaser if we actually publish, but it looks like these test runs are done with a dry run, so no manifest is generated. I'll add a conditional for this!

**Comment by cwaldren-ld** [comment]
Ok cool, is this ready for final review?

**Comment by rsoberano-ld** [comment]
> Ok cool, is this ready for final review?

I'd say so! Let's kick off one more manual publish dry run to make sure the binary provenance generation works, and I guess we'll have to wait for the next real release to see if the Docker provenance works, but it's not a huge deal if that fails to work the first time.

**Comment by cwaldren-ld** [comment]
https://github.com/launchdarkly/ld-relay/actions/runs/9422053445

**Comment by rsoberano-ld** [comment]
Awesome, binary provenance looks good! Ping me next time we do a real release and I can check on the container provenance

**Comment by rsoberano-ld** [comment]
(@cwaldren-ld can we approve/merge this PR in the meantime?)

**Comment by cwaldren-ld** [comment]
Oh darn. I thought this had been merged, but will do now. Release coming soon.

**Review by cwaldren-ld — APPROVED** [review]

**Pull request merged**
